package com.howard;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Integration1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  public void setDriver(WebDriver driver) {
    this.driver = driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  public void Login() {
    driver.get("http://wan.baidu.com/game?gameId=26588310&serverId=11082&idfrom=5056");
    driver.manage().window().setSize(new Dimension(677, 1239));
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(5000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
  }

  public void EquipmentBoss() {
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    System.out.println("`set speed` is a no-op in code export, use `pause` instead");
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    Integer times = 8;
    for(int i = 0; i < times; i++) {
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
      try {
        Thread.sleep(15000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      driver.findElement(By.cssSelector("canvas")).click();
    }
    driver.findElement(By.cssSelector("canvas")).click();
  }

  public void WholePeopleBoss() {
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(700);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(75000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
  }

  public void Daily() {
    System.out.println("`set speed` is a no-op in code export, use `pause` instead");
    Daily_Small();
    Daily_Big();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    Integer times = 9;
    for(int i = 0; i < times; i++) {
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
    }
    driver.findElement(By.cssSelector("canvas")).click();
  }
  public void Daily_Small() {
    Integer times = 7;
    for(int i = 0; i < times; i++) {
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
      try {
        Thread.sleep(50000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
  public void Daily_Big() {
    Integer times = 2;
    for(int i = 0; i < times; i++) {
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
      driver.findElement(By.cssSelector("canvas")).click();
      try {
        Thread.sleep(195000);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
  }
  public void Experience() {
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(130000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(200000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
  public void Griffin() {
    try {
      Thread.sleep(600);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(60000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(500);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(60000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(60000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(60000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    try {
      Thread.sleep(60000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
    driver.findElement(By.cssSelector("canvas")).click();
  }

  @Test
  public void Integration1() {
    Login();
//    EquipmentBoss();
//    WholePeopleBoss();
//    Daily();
//    Experience();
//    EquipmentBoss();
//    Griffin();
  }
}
